apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: gethomepage
  labels:
    app.kubernetes.io/name: homepage
secrets:
  - name: homepage
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: gethomepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: gethomepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/hfolguera?tab=repositories
  services.yaml: |
    - Infrastructure:
        - Router:
            icon: dd-wrt.png
            href: http://192.168.1.1
            description: Mitrastar HGU gpt-2541gnac
        - Proxmox:
            icon: proxmox.png
            href: https://cf-vm-node1.calfolguera.com:8006/
            description: Hypervisor
            siteMonitor: https://cf-vm-node1.calfolguera.com:8006/
            widget:
              type: proxmox
              url: https://192.168.1.3:8006
              username: api@pam!homepage
              password: 22073850-c8a8-40ca-be03-3cf7e7277d66
        - Synology ds220j:
            icon: synology.png
            href: https://192.168.1.11:5001/
            description: Synology NAS
            siteMonitor: https://192.168.1.11:5001/
        - Zyxel NSA310S:
            href: http://192.168.1.12
            description: Zyxel NAS
            siteMonitor: http://192.168.1.12

    - Services:
        - Argocd:
            icon: argo-cd.png
            href: https://argocd.calfolguera.freemyip.com
            description: Declarative GitOps CD for Kubernetes
            siteMonitor: https://argocd.calfolguera.freemyip.com
            statusStyle: 'dot'
        - Jenkins:
            icon: jenkins.png
            href: https://jenkins.calfolguera.freemyip.com
            description: Build great things at any scale
            siteMonitor: https://jenkins.calfolguera.freemyip.com
            statusStyle: 'dot'
        - AWX:
            icon: ansible.png
            href: https://awx.calfolguera.freemyip.com
            description: Provides a web-based user interface, REST API, and task engine built on top of Ansible
            siteMonitor: https://awx.calfolguera.freemyip.com
            statusStyle: 'dot'
        - Grafana:
            icon: grafana.png
            href: https://grafana.calfolguera.freemyip.com
            description: Observability in minutes
            siteMonitor: https://grafana.calfolguera.freemyip.com
            statusStyle: 'dot'
        - Kibana:
            icon: kibana.png
            href: https://kibana.calfolguera.freemyip.com
            description: Explore, Visualize, Discover Data
            siteMonitor: https://kibana.calfolguera.freemyip.com
            statusStyle: 'dot'
        - N8N:
            icon: n8n.png
            href: https://n8n.calfolguera.freemyip.com
            description: Automate Workflows Easily
            siteMonitor: https://n8n.calfolguera.freemyip.com
            statusStyle: 'dot'
        - Wordpress:
            icon: wordpress.png
            href: https://wordpress.calfolguera.freemyip.com
            description: Do it all with WordPress
            siteMonitor: https://wordpress.calfolguera.freemyip.com
            statusStyle: 'dot'
        - Prometheus:
            icon: prometheus.png
            href: http://calfolguera.ddns.net:9090
            description: An open-source monitoring system
            siteMonitor: http://calfolguera.ddns.net:9090
            statusStyle: 'dot'
            widget:
              type: prometheus
              url: http://calfolguera.ddns.net:9090
        - NTFY:
            icon: ntfy.png
            href: https://ntfy.calfolguera.freemyip.com
            description: Simple HTTP-based pub-sub notification service
            siteMonitor: https://ntfy.calfolguera.freemyip.com
            statusStyle: 'dot'

    - Smarthome:
        - Home Assistant:
            icon: home-assistant.png
            href: http://homeassistant.calfolguera.com
            description: Home Assistant
            siteMonitor: http://homeassistant.calfolguera.com
            widget:
              type: homeassistant
              url: http://homeassistant.calfolguera.com:8123
              key: access_token
        - Plex:
            icon: plex.png
            href: http://192.168.1.11:32400/web
            description: Plex Media Server
            siteMonitor: http://192.168.1.11:32400/web
            widget:
              type: plex
              url: http://192.168.1.11:32400
              key: j9csoswLX6swa4gA9YgV
        - Adguard:
            icon: adguard-home.svg
            href: https://adguard.calfolguera.freemyip.com
            description: Surf the Web ad-free and safely. Shields up!
            siteMonitor: https://adguard.calfolguera.freemyip.com
            statusStyle: 'dot'
        - Vaultwarden:
            icon: vaultwarden.svg
            href: https://vaultwarden.calfolguera.freemyip.com
            description: The community driven password manager
            siteMonitor: https://vaultwarden.calfolguera.freemyip.com
            statusStyle: 'dot'
        - Microbin:
            icon: microbin.png
            href: https://microbin.calfolguera.freemyip.com
            description: MicroBin is a super tiny, feature rich, configurable, self-contained and self-hosted paste bin web application
            siteMonitor: https://microbin.calfolguera.freemyip.com
            statusStyle: 'dot'
        - Uptime Kuma:
            icon: uptime-kuma.svg
            href: https://uptimekuma.calfolguera.freemyip.com
            description: A self-hosted monitoring tool
            siteMonitor: https://uptimekuma.calfolguera.freemyip.com
            statusStyle: 'dot'
            widget:
              type: uptimekuma
              url: https://uptimekuma.calfolguera.freemyip.com
              slug: default
        - Frigate:
            icon: frigate.svg
            href: https://frigate.calfolguera.freemyip.com
            description: Open source NVR built around real-time AI object detection
            siteMonitor: https://frigate.calfolguera.freemyip.com
            statusStyle: 'dot'
        - Immich:
            icon: immich.svg
            href: https://immich.calfolguera.freemyip.com
            description: Easily back up, organize, and manage your photos on your own server
            siteMonitor: https://immich.calfolguera.freemyip.com
            statusStyle: 'dot'

    - Nerea:
        - OCI Tenant:
            icon: oracle-cloud.png
            href: https://cloud.oracle.com/?tenant=nereamena&provider=default
            description: Oracle Cloud Infrastructure
        - Wordpress:
            icon: wordpress.png
            href: https://nereamenapsicologia.com
            description: Website
            siteMonitor: https://nereamenapsicologia.com
        - InvoiceNinja:
            icon: invoice-ninja-light.svg
            href: https://invoiceninja.calfolguera.freemyip.com
            description: CRM
            siteMonitor: https://invoiceninja.calfolguera.freemyip.com
    - Misc:
        - Ghostfolio:
            icon: ghostfolio.svg
            href: https://ghostfolio.calfolguera.freemyip.com
            description: Open source dashboard for your personal finances
        - Hashicorp Vault:
            icon: hashicorp-vault.svg
            href: https://vault.calfolguera.freemyip.com
            description: Secure, store, and tightly control access to tokens, passwords, certificates, encryption keys for protecting secrets, and other sensitive data
        - Lubelogger:
            icon: lubelogger.svg
            href: https://lubelogger.calfolguera.freemyip.com
            description: Self-Hosted, Open-Source, Unconventionally-Named Vehicle Maintenance Records and Fuel Mileage Tracker
        - RomM:
            icon: romm.svg
            href: https://romm.calfolguera.freemyip.com
            description: Scan, enrich, browse and play your game collection
        - Mealie:
            icon: mealie.svg
            href: https://mealie.calfolguera.freemyip.com
            description: Intuitive and easy to use recipe management app


  widgets.yaml: |
    # - kubernetes:
    #     cluster:
    #       show: true
    #       cpu: true
    #       memory: true
    #       showLabel: true
    #       label: "cluster"
    #     nodes:
    #       show: true
    #       cpu: true
    #       memory: true
    #       showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.containo.us
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: gethomepage
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: gethomepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: gethomepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
          - name: HOMEPAGE_ALLOWED_HOSTS
            value: "homepage.calfolguera.freemyip.com,192.168.1.7,192.168.1.8,192.168.1.9:3000"
          volumeMounts:
            - mountPath: /app/config/custom.js
              name: homepage-config
              subPath: custom.js
            - mountPath: /app/config/custom.css
              name: homepage-config
              subPath: custom.css
            - mountPath: /app/config/bookmarks.yaml
              name: homepage-config
              subPath: bookmarks.yaml
            - mountPath: /app/config/docker.yaml
              name: homepage-config
              subPath: docker.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: homepage-config
              subPath: kubernetes.yaml
            - mountPath: /app/config/services.yaml
              name: homepage-config
              subPath: services.yaml
            - mountPath: /app/config/settings.yaml
              name: homepage-config
              subPath: settings.yaml
            - mountPath: /app/config/widgets.yaml
              name: homepage-config
              subPath: widgets.yaml
            - mountPath: /app/config/logs
              name: logs
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: logs
          emptyDir: {}
#---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: homepage
#   namespace: gethomepage
#   labels:
#     app.kubernetes.io/name: homepage
#   annotations:
#     gethomepage.dev/description: Dynamically Detected Homepage
#     gethomepage.dev/enabled: "true"
#     gethomepage.dev/group: Cluster Management
#     gethomepage.dev/icon: homepage.png
#     gethomepage.dev/name: Homepage
# spec:
#   rules:
#     - host: "homepage.calfolguera.freemyip.com"
#       http:
#         paths:
#           - path: "/"
#             pathType: Prefix
#             backend:
#               service:
#                 name: homepage
#                 port:
#                   number: 3000
